import type { UnicodeInterval } from "@/types/epdfont";

// Unicode range definitions with metadata
export interface UnicodeRangeInfo {
  id: string;
  name: string;
  description: string;
  intervals: UnicodeInterval[];
  category: string;
  defaultEnabled: boolean;
  charCount: number; // approximate character count
}

// All Unicode ranges organized by category
export const UNICODE_RANGES: UnicodeRangeInfo[] = [
  // ===== Latin & European =====
  {
    id: "basicLatin",
    name: "Basic Latin",
    description: "ASCII letters, digits, punctuation (0x0000-0x007F)",
    intervals: [{ start: 0x0000, end: 0x007f }],
    category: "Latin & European",
    defaultEnabled: true,
    charCount: 128,
  },
  {
    id: "latin1Supplement",
    name: "Latin-1 Supplement",
    description:
      "Accented characters for Western European languages (0x0080-0x00FF)",
    intervals: [{ start: 0x0080, end: 0x00ff }],
    category: "Latin & European",
    defaultEnabled: true,
    charCount: 128,
  },
  {
    id: "latinExtendedA",
    name: "Latin Extended-A",
    description: "Eastern European and Baltic languages (0x0100-0x017F)",
    intervals: [{ start: 0x0100, end: 0x017f }],
    category: "Latin & European",
    defaultEnabled: true,
    charCount: 128,
  },
  {
    id: "latinExtendedB",
    name: "Latin Extended-B",
    description: "Additional Latin characters (0x0180-0x024F)",
    intervals: [{ start: 0x0180, end: 0x024f }],
    category: "Latin & European",
    defaultEnabled: false,
    charCount: 208,
  },
  {
    id: "combiningDiacriticals",
    name: "Combining Diacritical Marks",
    description: "Accent marks for extended Latin rendering (0x0300-0x036F)",
    intervals: [{ start: 0x0300, end: 0x036f }],
    category: "Latin & European",
    defaultEnabled: true,
    charCount: 112,
  },
  {
    id: "greek",
    name: "Greek & Coptic",
    description: "Greek alphabet for science/math (0x0370-0x03FF)",
    intervals: [{ start: 0x0370, end: 0x03ff }],
    category: "Latin & European",
    defaultEnabled: false,
    charCount: 144,
  },
  {
    id: "cyrillic",
    name: "Cyrillic",
    description: "Russian, Ukrainian, Bulgarian, etc. (0x0400-0x04FF)",
    intervals: [{ start: 0x0400, end: 0x04ff }],
    category: "Latin & European",
    defaultEnabled: true,
    charCount: 256,
  },
  {
    id: "cyrillicSupplement",
    name: "Cyrillic Supplement",
    description: "Additional Cyrillic characters (0x0500-0x052F)",
    intervals: [{ start: 0x0500, end: 0x052f }],
    category: "Latin & European",
    defaultEnabled: false,
    charCount: 48,
  },

  // ===== Middle Eastern =====
  {
    id: "arabic",
    name: "Arabic",
    description: "Arabic script (0x0600-0x06FF)",
    intervals: [{ start: 0x0600, end: 0x06ff }],
    category: "Middle Eastern",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "hebrew",
    name: "Hebrew",
    description: "Hebrew alphabet (0x0590-0x05FF)",
    intervals: [{ start: 0x0590, end: 0x05ff }],
    category: "Middle Eastern",
    defaultEnabled: false,
    charCount: 112,
  },

  // ===== South & Southeast Asian =====
  {
    id: "thai",
    name: "Thai",
    description: "Thai script (0x0E00-0x0E7F)",
    intervals: [{ start: 0x0e00, end: 0x0e7f }],
    category: "South & Southeast Asian",
    defaultEnabled: false,
    charCount: 128,
  },

  // ===== Punctuation & Symbols =====
  {
    id: "generalPunctuation",
    name: "General Punctuation",
    description: "Smart quotes, dashes, ellipsis, spaces (0x2000-0x206F)",
    intervals: [{ start: 0x2000, end: 0x206f }],
    category: "Punctuation & Symbols",
    defaultEnabled: true,
    charCount: 112,
  },
  {
    id: "currencySymbols",
    name: "Currency Symbols",
    description: "Euro, Pound, Yen, etc. (0x20A0-0x20CF)",
    intervals: [{ start: 0x20a0, end: 0x20cf }],
    category: "Punctuation & Symbols",
    defaultEnabled: true,
    charCount: 48,
  },
  {
    id: "letterlikeSymbols",
    name: "Letterlike Symbols",
    description: "Trademark, copyright, etc. (0x2100-0x214F)",
    intervals: [{ start: 0x2100, end: 0x214f }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 80,
  },
  {
    id: "numberForms",
    name: "Number Forms",
    description: "Roman numerals, fractions (0x2150-0x218F)",
    intervals: [{ start: 0x2150, end: 0x218f }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 64,
  },
  {
    id: "arrows",
    name: "Arrows",
    description: "Arrow symbols (0x2190-0x21FF)",
    intervals: [{ start: 0x2190, end: 0x21ff }],
    category: "Punctuation & Symbols",
    defaultEnabled: true,
    charCount: 112,
  },
  {
    id: "mathOperators",
    name: "Mathematical Operators",
    description: "Math symbols (0x2200-0x22FF)",
    intervals: [{ start: 0x2200, end: 0x22ff }],
    category: "Punctuation & Symbols",
    defaultEnabled: true,
    charCount: 256,
  },
  {
    id: "miscTechnical",
    name: "Misc. Technical",
    description: "Technical symbols (0x2300-0x23FF)",
    intervals: [{ start: 0x2300, end: 0x23ff }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "boxDrawing",
    name: "Box Drawing",
    description: "Box drawing characters (0x2500-0x257F)",
    intervals: [{ start: 0x2500, end: 0x257f }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 128,
  },
  {
    id: "blockElements",
    name: "Block Elements",
    description: "Block and shade characters (0x2580-0x259F)",
    intervals: [{ start: 0x2580, end: 0x259f }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "geometricShapes",
    name: "Geometric Shapes",
    description: "Circles, squares, triangles (0x25A0-0x25FF)",
    intervals: [{ start: 0x25a0, end: 0x25ff }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "miscSymbols",
    name: "Misc. Symbols",
    description: "Various symbols (0x2600-0x26FF)",
    intervals: [{ start: 0x2600, end: 0x26ff }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "dingbats",
    name: "Dingbats",
    description: "Decorative symbols (0x2700-0x27BF)",
    intervals: [{ start: 0x2700, end: 0x27bf }],
    category: "Punctuation & Symbols",
    defaultEnabled: false,
    charCount: 192,
  },

  // ===== CJK (East Asian) =====
  {
    id: "cjkSymbols",
    name: "CJK Symbols & Punctuation",
    description: "CJK punctuation marks (0x3000-0x303F)",
    intervals: [{ start: 0x3000, end: 0x303f }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 64,
  },
  {
    id: "hiragana",
    name: "Hiragana",
    description: "Japanese Hiragana (0x3040-0x309F)",
    intervals: [{ start: 0x3040, end: 0x309f }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "katakana",
    name: "Katakana",
    description: "Japanese Katakana (0x30A0-0x30FF)",
    intervals: [{ start: 0x30a0, end: 0x30ff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "katakanaPhonetic",
    name: "Katakana Phonetic Extensions",
    description: "Katakana extensions (0x31F0-0x31FF)",
    intervals: [{ start: 0x31f0, end: 0x31ff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 16,
  },
  {
    id: "hangulJamo",
    name: "Hangul Jamo",
    description: "Korean Jamo consonants/vowels (0x1100-0x11FF)",
    intervals: [{ start: 0x1100, end: 0x11ff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "hangulCompatJamo",
    name: "Hangul Compatibility Jamo",
    description: "Korean compatibility Jamo (0x3130-0x318F)",
    intervals: [{ start: 0x3130, end: 0x318f }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "hangulJamoExtA",
    name: "Hangul Jamo Extended-A",
    description: "Old Korean Jamo (0xA960-0xA97F)",
    intervals: [{ start: 0xa960, end: 0xa97f }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "hangulSyllables",
    name: "Hangul Syllables",
    description: "Complete Korean syllables (0xAC00-0xD7AF) - Large!",
    intervals: [{ start: 0xac00, end: 0xd7af }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 11184,
  },
  {
    id: "hangulJamoExtB",
    name: "Hangul Jamo Extended-B",
    description: "Old Korean Jamo (0xD7B0-0xD7FF)",
    intervals: [{ start: 0xd7b0, end: 0xd7ff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 80,
  },
  {
    id: "cjkRadicalsSupplement",
    name: "CJK Radicals Supplement",
    description: "CJK radicals (0x2E80-0x2EFF)",
    intervals: [{ start: 0x2e80, end: 0x2eff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 128,
  },
  {
    id: "kangxiRadicals",
    name: "Kangxi Radicals",
    description: "Kangxi dictionary radicals (0x2F00-0x2FDF)",
    intervals: [{ start: 0x2f00, end: 0x2fdf }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 224,
  },
  {
    id: "cjkUnified",
    name: "CJK Unified Ideographs",
    description: "Main CJK characters (0x4E00-0x9FFF) - Very Large!",
    intervals: [{ start: 0x4e00, end: 0x9fff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 20992,
  },
  {
    id: "cjkExtensionA",
    name: "CJK Extension A",
    description: "CJK Extension A (0x3400-0x4DBF) - Large!",
    intervals: [{ start: 0x3400, end: 0x4dbf }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 6592,
  },
  {
    id: "cjkCompatIdeographs",
    name: "CJK Compat. Ideographs",
    description: "CJK compatibility (0xF900-0xFAFF)",
    intervals: [{ start: 0xf900, end: 0xfaff }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 512,
  },
  {
    id: "cjkCompatForms",
    name: "CJK Compatibility Forms",
    description: "CJK compatibility forms (0xFE30-0xFE4F)",
    intervals: [{ start: 0xfe30, end: 0xfe4f }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "halfwidthFullwidth",
    name: "Halfwidth & Fullwidth Forms",
    description: "Width variants (0xFF00-0xFFEF)",
    intervals: [{ start: 0xff00, end: 0xffef }],
    category: "CJK (East Asian)",
    defaultEnabled: false,
    charCount: 240,
  },

  // ===== CJK Extensions (SIP - Supplementary Ideographic Plane) =====
  {
    id: "cjkExtensionB",
    name: "CJK Extension B",
    description: "한중일 통합 한자 확장 B (U+20000-U+2A6DF) - Very Large!",
    intervals: [{ start: 0x20000, end: 0x2a6df }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 42720,
  },
  {
    id: "cjkExtensionC",
    name: "CJK Extension C",
    description: "한중일 통합 한자 확장 C (U+2A700-U+2B73F)",
    intervals: [{ start: 0x2a700, end: 0x2b73f }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 4160,
  },
  {
    id: "cjkExtensionD",
    name: "CJK Extension D",
    description: "한중일 통합 한자 확장 D (U+2B740-U+2B81F)",
    intervals: [{ start: 0x2b740, end: 0x2b81f }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 224,
  },
  {
    id: "cjkExtensionE",
    name: "CJK Extension E",
    description: "한중일 통합 한자 확장 E (U+2B820-U+2CEAF)",
    intervals: [{ start: 0x2b820, end: 0x2ceaf }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 5776,
  },
  {
    id: "cjkExtensionF",
    name: "CJK Extension F",
    description: "한중일 통합 한자 확장 F (U+2CEB0-U+2EBEF)",
    intervals: [{ start: 0x2ceb0, end: 0x2ebef }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 7488,
  },
  {
    id: "cjkCompatIdeographsSupplement",
    name: "CJK Compat. Ideographs Supplement",
    description: "한중일 호환용 한자 보충 (U+2F800-U+2FA1F)",
    intervals: [{ start: 0x2f800, end: 0x2fa1f }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 544,
  },
  {
    id: "cjkExtensionG",
    name: "CJK Extension G",
    description: "한중일 통합 한자 확장 G (U+30000-U+3134F)",
    intervals: [{ start: 0x30000, end: 0x3134f }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 4944,
  },
  {
    id: "cjkExtensionH",
    name: "CJK Extension H",
    description: "한중일 통합 한자 확장 H (U+31350-U+323AF)",
    intervals: [{ start: 0x31350, end: 0x323af }],
    category: "CJK Extensions (SIP)",
    defaultEnabled: false,
    charCount: 4192,
  },

  // ===== Publishing & Documents =====
  {
    id: "superscriptsSubscripts",
    name: "Superscripts & Subscripts",
    description: "위첨자, 아래첨자 (0x2070-0x209F)",
    intervals: [{ start: 0x2070, end: 0x209f }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 48,
  },
  {
    id: "enclosedAlphanumerics",
    name: "Enclosed Alphanumerics",
    description: "원문자, 괄호문자 ①②③ (0x2460-0x24FF)",
    intervals: [{ start: 0x2460, end: 0x24ff }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 160,
  },
  {
    id: "enclosedCjkLetters",
    name: "Enclosed CJK Letters",
    description: "원문자 한글/한자 ㉠㉡㉢ (0x3200-0x32FF)",
    intervals: [{ start: 0x3200, end: 0x32ff }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "cjkCompatibility",
    name: "CJK Compatibility",
    description: "CJK 호환 문자 ㍿㎜㎝ (0x3300-0x33FF)",
    intervals: [{ start: 0x3300, end: 0x33ff }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "enclosedIdeographicSupplement",
    name: "Enclosed Ideographic Supplement",
    description: "원문자 보충 🈚🈯 (U+1F200-U+1F2FF)",
    intervals: [{ start: 0x1f200, end: 0x1f2ff }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "smallFormVariants",
    name: "Small Form Variants",
    description: "작은 형태 변형 (0xFE50-0xFE6F)",
    intervals: [{ start: 0xfe50, end: 0xfe6f }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "verticalForms",
    name: "Vertical Forms",
    description: "세로쓰기용 기호 (0xFE10-0xFE1F)",
    intervals: [{ start: 0xfe10, end: 0xfe1f }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 16,
  },
  {
    id: "ideographicSymbols",
    name: "Ideographic Symbols & Punctuation",
    description: "표의 문자 기호 (U+16FE0-U+16FFF)",
    intervals: [{ start: 0x16fe0, end: 0x16fff }],
    category: "Publishing & Documents",
    defaultEnabled: false,
    charCount: 32,
  },

  // ===== Additional Scripts =====
  {
    id: "latinExtendedAdditional",
    name: "Latin Extended Additional",
    description: "라틴 확장 추가 - 베트남어 등 (0x1E00-0x1EFF)",
    intervals: [{ start: 0x1e00, end: 0x1eff }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "latinExtendedC",
    name: "Latin Extended-C",
    description: "라틴 확장 C (0x2C60-0x2C7F)",
    intervals: [{ start: 0x2c60, end: 0x2c7f }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "latinExtendedD",
    name: "Latin Extended-D",
    description: "라틴 확장 D (0xA720-0xA7FF)",
    intervals: [{ start: 0xa720, end: 0xa7ff }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 224,
  },
  {
    id: "latinExtendedE",
    name: "Latin Extended-E",
    description: "라틴 확장 E (0xAB30-0xAB6F)",
    intervals: [{ start: 0xab30, end: 0xab6f }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 64,
  },
  {
    id: "greekExtended",
    name: "Greek Extended",
    description: "그리스어 확장 (0x1F00-0x1FFF)",
    intervals: [{ start: 0x1f00, end: 0x1fff }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "cyrillicExtendedA",
    name: "Cyrillic Extended-A",
    description: "키릴 확장 A (0x2DE0-0x2DFF)",
    intervals: [{ start: 0x2de0, end: 0x2dff }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "cyrillicExtendedB",
    name: "Cyrillic Extended-B",
    description: "키릴 확장 B (0xA640-0xA69F)",
    intervals: [{ start: 0xa640, end: 0xa69f }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "cyrillicExtendedC",
    name: "Cyrillic Extended-C",
    description: "키릴 확장 C (0x1C80-0x1C8F)",
    intervals: [{ start: 0x1c80, end: 0x1c8f }],
    category: "Additional Scripts",
    defaultEnabled: false,
    charCount: 16,
  },

  // ===== IPA & Phonetics =====
  {
    id: "ipaExtensions",
    name: "IPA Extensions",
    description: "국제음성기호 (0x0250-0x02AF)",
    intervals: [{ start: 0x0250, end: 0x02af }],
    category: "IPA & Phonetics",
    defaultEnabled: false,
    charCount: 96,
  },
  {
    id: "phoneticExtensions",
    name: "Phonetic Extensions",
    description: "음성 확장 (0x1D00-0x1D7F)",
    intervals: [{ start: 0x1d00, end: 0x1d7f }],
    category: "IPA & Phonetics",
    defaultEnabled: false,
    charCount: 128,
  },
  {
    id: "phoneticExtensionsSupplement",
    name: "Phonetic Extensions Supplement",
    description: "음성 확장 보충 (0x1D80-0x1DBF)",
    intervals: [{ start: 0x1d80, end: 0x1dbf }],
    category: "IPA & Phonetics",
    defaultEnabled: false,
    charCount: 64,
  },
  {
    id: "spacingModifierLetters",
    name: "Spacing Modifier Letters",
    description: "간격 수정 문자 (0x02B0-0x02FF)",
    intervals: [{ start: 0x02b0, end: 0x02ff }],
    category: "IPA & Phonetics",
    defaultEnabled: false,
    charCount: 80,
  },

  // ===== Mathematical & Technical =====
  {
    id: "mathAlphanumericSymbols",
    name: "Math Alphanumeric Symbols",
    description: "수학 알파벳 기호 (U+1D400-U+1D7FF)",
    intervals: [{ start: 0x1d400, end: 0x1d7ff }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 1024,
  },
  {
    id: "supplementalMathOperators",
    name: "Supplemental Math Operators",
    description: "수학 연산자 보충 (0x2A00-0x2AFF)",
    intervals: [{ start: 0x2a00, end: 0x2aff }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "miscMathSymbolsA",
    name: "Misc. Math Symbols-A",
    description: "기타 수학 기호 A (0x27C0-0x27EF)",
    intervals: [{ start: 0x27c0, end: 0x27ef }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 48,
  },
  {
    id: "miscMathSymbolsB",
    name: "Misc. Math Symbols-B",
    description: "기타 수학 기호 B (0x2980-0x29FF)",
    intervals: [{ start: 0x2980, end: 0x29ff }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 128,
  },
  {
    id: "supplementalArrows",
    name: "Supplemental Arrows",
    description:
      "화살표 보충 A+B+C (0x27F0-0x27FF, 0x2900-0x297F, U+1F800-U+1F8FF)",
    intervals: [
      { start: 0x27f0, end: 0x27ff },
      { start: 0x2900, end: 0x297f },
      { start: 0x1f800, end: 0x1f8ff },
    ],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 400,
  },
  {
    id: "opticalCharacterRecognition",
    name: "Optical Character Recognition",
    description: "광학 문자 인식 (0x2440-0x245F)",
    intervals: [{ start: 0x2440, end: 0x245f }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 32,
  },
  {
    id: "controlPictures",
    name: "Control Pictures",
    description: "제어 문자 그림 (0x2400-0x243F)",
    intervals: [{ start: 0x2400, end: 0x243f }],
    category: "Mathematical & Technical",
    defaultEnabled: false,
    charCount: 64,
  },

  // ===== Emoji & Pictographs =====
  {
    id: "miscSymbolsPictographs",
    name: "Misc. Symbols & Pictographs",
    description: "기타 기호 및 픽토그램 (U+1F300-U+1F5FF)",
    intervals: [{ start: 0x1f300, end: 0x1f5ff }],
    category: "Emoji & Pictographs",
    defaultEnabled: false,
    charCount: 768,
  },
  {
    id: "emoticons",
    name: "Emoticons",
    description: "이모티콘 (U+1F600-U+1F64F)",
    intervals: [{ start: 0x1f600, end: 0x1f64f }],
    category: "Emoji & Pictographs",
    defaultEnabled: false,
    charCount: 80,
  },
  {
    id: "transportMapSymbols",
    name: "Transport & Map Symbols",
    description: "교통 및 지도 기호 (U+1F680-U+1F6FF)",
    intervals: [{ start: 0x1f680, end: 0x1f6ff }],
    category: "Emoji & Pictographs",
    defaultEnabled: false,
    charCount: 128,
  },
  {
    id: "supplementalSymbolsPictographs",
    name: "Supplemental Symbols & Pictographs",
    description: "보충 기호 및 픽토그램 (U+1F900-U+1F9FF)",
    intervals: [{ start: 0x1f900, end: 0x1f9ff }],
    category: "Emoji & Pictographs",
    defaultEnabled: false,
    charCount: 256,
  },
  {
    id: "symbolsExtendedA",
    name: "Symbols & Pictographs Extended-A",
    description: "기호 및 픽토그램 확장 A (U+1FA00-U+1FA6F)",
    intervals: [{ start: 0x1fa00, end: 0x1fa6f }],
    category: "Emoji & Pictographs",
    defaultEnabled: false,
    charCount: 112,
  },

  // ===== Special & Private Use =====
  {
    id: "specials",
    name: "Specials",
    description: "특수 문자 (0xFFF0-0xFFFF)",
    intervals: [{ start: 0xfff0, end: 0xffff }],
    category: "Special & Private Use",
    defaultEnabled: false,
    charCount: 16,
  },
  {
    id: "privateUseArea",
    name: "Private Use Area (BMP)",
    description: "사용자 정의 영역 (0xE000-0xF8FF) - Large!",
    intervals: [{ start: 0xe000, end: 0xf8ff }],
    category: "Special & Private Use",
    defaultEnabled: false,
    charCount: 6400,
  },
];

// Group ranges by category
export const RANGE_CATEGORIES = Array.from(
  new Set(UNICODE_RANGES.map((r) => r.category)),
);

// Get default enabled range IDs
export const DEFAULT_ENABLED_RANGES = UNICODE_RANGES.filter(
  (r) => r.defaultEnabled,
).map((r) => r.id);

// Quick presets for common use cases (toggle-able)
// rangeIds contains ONLY the additional ranges for this preset (not including defaults)
export interface QuickPreset {
  id: string;
  name: string;
  description: string;
  rangeIds: string[]; // Only the unique ranges for this preset
  icon: string;
}

export const QUICK_PRESETS: QuickPreset[] = [
  {
    id: "korean",
    name: "한국어",
    description: "한글 음절, 자모, 호환 자모, CJK 기호, 원문자",
    rangeIds: [
      "hangulSyllables",
      "hangulJamo",
      "hangulCompatJamo",
      "cjkSymbols",
      "enclosedCjkLetters",
    ],
    icon: "🇰🇷",
  },
  {
    id: "hanja",
    name: "한자 (기본)",
    description: "CJK 통합 한자 (20,992자)",
    rangeIds: ["cjkUnified", "cjkSymbols", "kangxiRadicals"],
    icon: "漢",
  },
  {
    id: "hanjaExtended",
    name: "한자 (확장)",
    description: "CJK 한자 + 확장 A~H (약 9만자) - Very Large!",
    rangeIds: [
      "cjkUnified",
      "cjkExtensionA",
      "cjkExtensionB",
      "cjkExtensionC",
      "cjkExtensionD",
      "cjkExtensionE",
      "cjkExtensionF",
      "cjkExtensionG",
      "cjkExtensionH",
      "cjkCompatIdeographs",
      "cjkCompatIdeographsSupplement",
      "cjkSymbols",
      "kangxiRadicals",
      "cjkRadicalsSupplement",
    ],
    icon: "漢+",
  },
  {
    id: "japanese",
    name: "日本語",
    description: "히라가나, 가타카나, CJK 기호",
    rangeIds: [
      "hiragana",
      "katakana",
      "katakanaPhonetic",
      "cjkSymbols",
      "halfwidthFullwidth",
    ],
    icon: "🇯🇵",
  },
  {
    id: "chinese",
    name: "中文",
    description: "CJK 통합 한자, 기호, 병음",
    rangeIds: [
      "cjkUnified",
      "cjkSymbols",
      "cjkCompatIdeographs",
      "halfwidthFullwidth",
    ],
    icon: "🇨🇳",
  },
  {
    id: "fullwidth",
    name: "전각 문자",
    description: "전각/반각 폼, CJK 기호",
    rangeIds: ["halfwidthFullwidth", "cjkSymbols", "cjkCompatibility"],
    icon: "Ａ",
  },
  {
    id: "publishing",
    name: "출판/문서",
    description: "원문자, 위/아래첨자, 단위기호, 세로쓰기",
    rangeIds: [
      "superscriptsSubscripts",
      "enclosedAlphanumerics",
      "enclosedCjkLetters",
      "cjkCompatibility",
      "smallFormVariants",
      "verticalForms",
      "numberForms",
      "letterlikeSymbols",
    ],
    icon: "📖",
  },
  {
    id: "math",
    name: "수학 기호",
    description: "수학 연산자, 그리스어, 수학 알파벳",
    rangeIds: [
      "greek",
      "greekExtended",
      "numberForms",
      "letterlikeSymbols",
      "miscTechnical",
      "mathAlphanumericSymbols",
      "supplementalMathOperators",
      "miscMathSymbolsA",
      "miscMathSymbolsB",
      "supplementalArrows",
    ],
    icon: "∑",
  },
  {
    id: "symbols",
    name: "특수 문자",
    description: "기호, 딩뱃, 도형, 박스 그리기",
    rangeIds: [
      "miscSymbols",
      "dingbats",
      "geometricShapes",
      "boxDrawing",
      "blockElements",
    ],
    icon: "★",
  },
  {
    id: "european",
    name: "유럽어 확장",
    description: "라틴 확장, 그리스어, 키릴 확장",
    rangeIds: [
      "latinExtendedB",
      "latinExtendedC",
      "latinExtendedD",
      "latinExtendedE",
      "latinExtendedAdditional",
      "greek",
      "greekExtended",
      "cyrillicSupplement",
      "cyrillicExtendedA",
      "cyrillicExtendedB",
      "cyrillicExtendedC",
    ],
    icon: "🇪🇺",
  },
  {
    id: "multilingual",
    name: "다국어",
    description: "아랍어, 히브리어, 태국어, 베트남어",
    rangeIds: [
      "arabic",
      "hebrew",
      "thai",
      "latinExtendedAdditional", // Vietnamese
    ],
    icon: "🌍",
  },
  {
    id: "phonetics",
    name: "음성 기호",
    description: "IPA, 음성 확장, 간격 수정자",
    rangeIds: [
      "ipaExtensions",
      "phoneticExtensions",
      "phoneticExtensionsSupplement",
      "spacingModifierLetters",
    ],
    icon: "🗣️",
  },
  {
    id: "emoji",
    name: "이모지",
    description: "이모티콘, 픽토그램, 기호",
    rangeIds: [
      "miscSymbolsPictographs",
      "emoticons",
      "transportMapSymbols",
      "supplementalSymbolsPictographs",
      "symbolsExtendedA",
    ],
    icon: "😀",
  },
];
